# Generated by Django 5.2.8 on 2025-12-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['category', 'title']},
        ),
        migrations.AddField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('social-emotional', 'Social-Emotional'), ('cognitive', 'Cognitive'), ('physical', 'Physical'), ('language', 'Language')], default='social-emotional', max_length=20),
        ),
        migrations.AddField(
            model_name='milestone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='milestone_images/'),
        ),
    ]
