# Generated by Django 5.2.8 on 2026-01-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecd_app', '0002_alter_milestone_options_child_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='child_photos/'),
        ),
    ]
