# Generated by Django 5.2.8 on 2026-02-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecd_app', '0003_alter_child_age_alter_child_parent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elibrary',
            name='category',
            field=models.CharField(choices=[('Nutrition', 'Nutrition'), ('Psychology', 'Psychology'), ('Behavior', 'Behavior'), ('Sleep', 'Sleep'), ('Language', 'Language'), ('Safety', 'Safety')], default='Nutrition', max_length=50),
        ),
        migrations.AddField(
            model_name='elibrary',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
