# Generated by Django 5.2.8 on 2026-02-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecd_app', '0004_elibrary_category_elibrary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elibrary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='library_images/'),
        ),
    ]
