# Generated by Django 5.2.8 on 2026-02-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecd_app', '0005_alter_elibrary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='elibrary',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='library_images/'),
        ),
        migrations.AlterField(
            model_name='elibrary',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
