# Generated by Django 5.2.8 on 2026-04-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecd_app', '0007_followupmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='recommended_age',
        ),
        migrations.AddField(
            model_name='activity',
            name='age',
            field=models.CharField(blank=True, choices=[('Age 2-3', 'Age 2-3'), ('Age 3-4', 'Age 3-4'), ('Age 4-5', 'Age 4-5'), ('Age 5-6', 'Age 5-6')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='domain',
            field=models.CharField(blank=True, choices=[('Language', 'Language'), ('Cognitive', 'Cognitive'), ('Physical', 'Physical'), ('Creative', 'Creative'), ('Fine Motor', 'Fine Motor'), ('Social-Emotional', 'Social-Emotional'), ('Science', 'Science'), ('Math + Physical', 'Math + Physical')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.CharField(blank=True, help_text="e.g., '15 min', '20 min'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
