# Generated by Django 5.2.8 on 2026-05-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecd_app', '0010_followupmessage_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('social-emotional', 'Social-Emotional'), ('cognitive', 'Cognitive'), ('physical', 'Physical'), ('language', 'Language'), ('self-care', 'Self-Care & Independence'), ('executive-function', 'Executive Function & Attention')], default='social-emotional', max_length=20),
        ),
    ]
