# Generated by Django 5.2.8 on 2026-05-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecd_app', '0011_alter_milestone_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elibrary',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
