# Generated by Django 5.2.8 on 2026-05-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecd_app', '0012_alter_elibrary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elibrary',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
