# Generated by Django 5.2.8 on 2026-05-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecd_app', '0014_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.CharField(db_index=True, default='', max_length=500),
        ),
    ]
