# Generated by Django 5.2.8 on 2026-05-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecd_app', '0015_chatmessage_receiver_name_chatmessage_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='chat_documents/'),
        ),
    ]
