# Generated by Django 5.2.8 on 2026-05-27 22:52

import ecd_app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecd_app', '0016_chatmessage_document_and_message_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='document',
            field=models.FileField(blank=True, null=True, storage=ecd_app.storage_backends.ChatDocumentCloudinaryStorage(), upload_to='chat_documents/'),
        ),
    ]
